### ISSUE TITLE
login input fields clipped on failed login

### ISSUE THREAD

**Issue by kksubbu** [JurajKubelka/PharoSprint#15]
Start a fresh image.
Enter Name.
Enter a wrong name in login. e.g "mickey" instead of "mickey@fogbugz.com" and press enter
The login and password fields will move up below the title bar as show in the attached picture.
![screenshot from 2017-04-25 00-11-43](https://cloud.githubusercontent.com/assets/27622112/25353225/27a7bf0e-294c-11e7-8163-b1830b8e94b3.png)

I think this is because the long error message is adding a horizontal scroll to the bottom of the panel.

**Comment by JurajKubelka** [comment]
Thanks @kksubbu! 

I think the solution is to use Spec's TextModel instead of LabelModel. It looks like the LabelModel cannot be stripped to available space.

**Comment by JurajKubelka** [comment]
Fixed in https://bintray.com/jurajkubelka/PharoSprint/build/20170425-91#files 

Not perfectly, because it looks like that it is not possible to remove `GeneralScrollPane` widget from the Glamour framework. 

And there are still UI issues, with the `Update` button, that does not display the "Update" word. It is necessary to hover a mouse.

![screen shot 2017-04-25 at 14 45 07](https://cloud.githubusercontent.com/assets/465505/25399467/f1369984-29c5-11e7-94da-22089f0e32aa.png)

I have opened new issue #20.
