### ISSUE TITLE
Proposed issues with a "Resolved" state should go in "Done"

### ISSUE THREAD

**Issue by jecisc** [JurajKubelka/PharoSprint#8]
To avoid the creation of noise in the "Proposed" tab.

**Comment by JurajKubelka** [comment]
Hi @jecisc,

Thanks for the proposal. There are two options:

1. There is a case without SLICE (solution).
2. There is a case with a SLICE.

In the first case, someone has to solve it and propose changes. So, it is valid having it in *all* and/or *proposed* columns. 

The second case should be reviewed. And reviewing is a one way to contribute (during Pharo Sprints). For that reason, I thought it is good idea to keep Review Needed option in *all* and *proposed* columns. 

For a while, I thought having a *Review Needed* column is a good idea:

![screen shot 2017-04-24 at 10 59 07](https://cloud.githubusercontent.com/assets/465505/25340762/1b3dadec-28dd-11e7-93a1-21b363b3707b.png)

You can download it: https://bintray.com/jurajkubelka/PharoSprint/build/201704191457-64#files 

Then I removed it, as I have introduced sorting option:

![screen shot 2017-04-24 at 10 57 40](https://cloud.githubusercontent.com/assets/465505/25340779/270e688c-28dd-11e7-8e0d-6e183d51a434.png)

If we decide to keep "Review Needed" column, than, from my point of view, the workflow gets a bit more confusing (complex). It is then not clear if *done* cases should also appear *Review Needed* column, because they can be reviewed too.

But maybe having *Review Needed* column is anyway worth to have, because then it is more easy for less experienced developers what to choose.

What do you think?
